### ISSUE TITLE
Server response code 999

### ISSUE THREAD

**Issue by yogi-dmt** [sstrickx/yahoofinance-api#101]
I've been getting this a bunch lately doing bulk stock calculations. I know it's not an issue with the API itself but i was wondering if anyone knew what sort of delay i should set in between stock pulls so that it doesn't lock me out.

**Comment by sstrickx** [comment]
I don't really have an idea where they put the limit, maybe somebody else can provide some insight?

**Comment by fyang1024** [comment]
Server returned HTTP response code: 403 for URL: http://download.finance.yahoo.com/d/quotes.csv?s

It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

**Comment by sstrickx** [comment]
This issue didn't really have anything to do with the discontinuation of the service.
The error was happening when sending too many requests in a short period of time.
I'll close it since nobody seems to be able to provide details about at which point the usage is considered to be too heavy.

For info related to the discontinuation of the quotes CSV service on 2017-10-30, see #105
