### ISSUE TITLE
Stock.getHistory() not working anymore

### ISSUE THREAD

**Issue by fyang1024** [sstrickx/yahoofinance-api#113]
2017-11-19 12:22:40.677 INFO  y.quotes.query1v7.QuotesRequest - Sending request: https://query1.finance.yahoo.com/v7/finance/quote?symbols=WND.AX
2017-11-19 12:22:41.045 INFO  y.histquotes2.HistQuotes2Request - Sending request: https://query1.finance.yahoo.com/v7/finance/download/WND.AX?period1=1503410400&period2=1503842400&interval=1d&crumb=s7fVP68ndAs

The second request returns 
```
{
    "finance": {
        "error": {
            "code": "Unauthorized",
            "description": "Invalid cookie"
        }
    }
}
```

**Comment by sstrickx** [comment]
Could you check if you get the same error with other stocks?
Windlab was only listed quite recently, so maybe the historical data isn't made available that soon on Yahoo Finance and this caused an error. (seems to be working on my end at the moment, even though I only manage to retrieve 1 day)
Also, did you see that error for the second request in the logs, or did you get that when opening the link in your browser? It would be normal to have that error when you try to open the link in your browser since it will have a different cookie than the one used by the library, so the crumb that is sent with the request would be wrong in that case.

**Comment by fyang1024** [comment]
That could be the reason -- Yahoo Finance may push the data into historical quotes after a certain period. My program missed a couple of week's quotes for some recently listed stocks. I tried to load the missing quotes, but probably the historical data is not available yet. I will try to load them again in couple of weeks to see how it is going. Thank you for the great library.
