### ISSUE TITLE
 java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by DanielMartensson** [sstrickx/yahoofinance-api#133]
Hello!

I want to report a bug. When I run this code:

`Stock stock = YahooFinance.get("INTC");`

I got this error:

`java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

Thank you for creating this library.

**Comment by sstrickx** [comment]
Hi, this actually looks like your environment doesn't trust Yahoo's SSL certificates for some reason.
There can be several reasons for this. I would guess one of the following:

1. You're using a trustStore/keyStore that doesn't contain the DigiCert root certificate

2. You're behind a proxy which is replacing the SSL certificates in order to be able to process the content of your network traffic. In that case you'd have to run the JRE with a trustStore that contains the proxy's certificate (only if you really trust it).
