### ISSUE TITLE
Null Values

### ISSUE THREAD

**Issue by mattycass95** [sstrickx/yahoofinance-api#33]
Hi, thanks for this API been looking for something this simple.

It is not getting data however and when I run
        Stock stock = new Stock("INTC");
        stock.print();
All fields are left null (Except symbol = INTC)

Any idea why it isn't getting data?

**Comment by sstrickx** [comment]
Hi Matt,
In your code, there hasn't been a request to Yahoo Finance yet. It's a bit
difficult to explain since I'm on mobile now, but I'll get you a better
answer in the next few hours.

Hi, thanks for this API been looking for something this simple.

It is not getting data however and when I run
Stock stock = new Stock("INTC");
stock.print();
All fields are left null (Except symbol = INTC)

Any idea why it isn't getting data?

—
Reply to this email directly or view it on GitHub
<https://github.com/sstrickx/yahoofinance-api/issues/33>.

**Comment by sstrickx** [comment]
Your code doesn't have a request to Yahoo Finance yet. There's 2 alternative ways to fix this.
**1. Request it through the YahooFinance static methods**
```java
Stock stock = YahooFinance.get("INTC");
stock.print();
```
**2. Force a refresh of the stock's quote by using the [getQuote(boolean refresh)](http://financequotes-api.com/javadoc/yahoofinance/Stock.html#getQuote-boolean-) method**
```java
Stock stock = new Stock("INTC");
stock.getQuote(true);
stock.print();
```
This will automatically also load/refresh the statistics and dividend data.
