### ISSUE TITLE
After midnight: FileNotFoundException due to URL not working

### ISSUE THREAD

**Issue by DennisVDB** [sstrickx/yahoofinance-api#59]
The API doesn't work anymore after precisely midnight but works again in the morning (I don't have a more specific time). The links for downloading the CSVs do not work and give an Error 404.

I get the following Log messages and stack trace:
`Sep 01, 2016 1:12:14 AM yahoofinance.histquotes.HistQuotesRequest getResult
INFO: Sending request: http://ichart.yahoo.com/table.csv?s=MSFT&a=7&b=31&c=2016&d=8&e=1&f=2016&g=d&ignore=.csv
Sep 01, 2016 1:12:14 AM yahoofinance.histquotes.HistQuotesRequest getResult
INFO: Sending request: http://ichart.yahoo.com/table.csv?s=GOOG&a=7&b=31&c=2016&d=8&e=1&f=2016&g=d&ignore=.csv
Sep 01, 2016 1:12:14 AM yahoofinance.histquotes.HistQuotesRequest getResult
INFO: Sending request: http://ichart.yahoo.com/table.csv?s=AAPL&a=7&b=31&c=2016&d=8&e=1&f=2016&g=d&ignore=.csv
Error: java.io.FileNotFoundException: http://ichart.yahoo.com/table.csv?s=AAPL&a=7&b=31&c=2016&d=8&e=1&f=2016&g=d&ignore=.csv
sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834)
sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
yahoofinance.histquotes.HistQuotesRequest.getResult(HistQuotesRequest.java:117)
yahoofinance.Stock.getHistory(Stock.java:290)
yahoofinance.YahooFinance.fetchHistoricalQuotes(YahooFinance.java:380)
yahoofinance.YahooFinance.getQuotes(YahooFinance.java:374)
yahoofinance.YahooFinance.get(YahooFinance.java:166)
data.YahooHistoricalDataFetcher$$anonfun$historicalPrices$1.apply(YahooHistoricalDataFetcher.scala:31)
data.YahooHistoricalDataFetcher$$anonfun$historicalPrices$1.apply(YahooHistoricalDataFetcher.scala:32)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

**Comment by derrix060** [comment]
Unfortunately this is from yahoo side. What time is there from utc? I will do some tests later, but I think that I know where is the problem, is from default interval be month and you are asking from a pretty recent data. I will check this.

Sent from my Samsung device

-------- Original message --------

**Comment by sstrickx** [comment]
Indeed, @derrix060  is probably right on this one.
The issue looks very similar to #19 . The fix for that issue was not fully correct as pointed out in PR #56 .
The service doesn't suddenly stop working after midnight. My guess would be the following:
Right after midnight (in your timezone), your program starts sending requests for historical quotes on the new date range (yesterday -> today). In this case, before midnight: 2016-08-30 -> 2016-08-31, after midnight: 2016-08-31 -> 2016-09-01. However, this historical data for your requested stock is not yet available from Yahoo Finance at that point in time. This results in the error you're getting.
It's not clear when the historical data becomes available and it probably depends on the exchange. For MSFT it seems to be between 10PM UTC - 3AM UTC.

We should maybe catch the exception and log a warning message about this before re-throwing it. (exceptions in this library should be handled a bit differently in general, but that will be for the next major-version change as it would break compatibility with current implementations)

**Comment by sstrickx** [comment]
Exception handling to be improved in 4.0.0: #68
