### ISSUE TITLE
Retrieving Index

### ISSUE THREAD

**Issue by kingbd** [sstrickx/yahoofinance-api#61]
Hi using the API to retrieve index quotes. The S&P 500 (^GSPC) and NASDAQ (^IXIC) are working but the Dow (^DJI) returns all N/A. Is it something in the way yahoo is packaging the data for this index or is there a different symbol for Dow even though on their site it is ^DJI. Thanks

**Comment by sstrickx** [comment]
Hi,

Seems like Yahoo is no longer allowed to make the data available like that for the Dow Jones Index. (since 2010) Originally you could still use **INDU** as an alternative, but this has been blocked as well in the meantime.

I got this from an old question on StackOverflow: http://stackoverflow.com/questions/3679870/yahoo-finance-csv-file-will-not-return-dow-jones-dji
> Thank you for writing to Yahoo! Finance. I understand you're reporting that you cannot download CSV data for ^DJI. I can certainly give you more information about this. The limitation you are encountering is due to restrictions by the Dow Jones Index. Yahoo! is no longer able to provide Dow Jones Index data in this manner. I apologize for any inconvenience caused. Please let me know if I can be of further assistance. Thank you again for contacting Yahoo! Finance. Regards, Brett Yahoo! Finance Customer Care
